apiVersion: v1
kind: Pod
metadata:
  name: kaniko
spec:
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:latest
    args: ["--dockerfile=Dockerfile",
            "--context=git://github.com/bharatmicrosystems/kubernetes-kaniko-nginx.git#refs/heads/master",
            "--destination=bharamicrosystems/nginx:v4"]
    volumeMounts:
      - name: kaniko-secret
        mountPath: "/kaniko/.docker"
      - name: dockerfile-storage
        mountPath: "/workspace"
  restartPolicy: Never
  initContainers:
  - name: init-kaniko
    image: yauritux/busybox-curl
    imagePullPolicy: IfNotPresent
    command: ["sh", "-c", "curl -k -o /workspace/Dockerfile https://raw.githubusercontent.com/bharatmicrosystems/kubernetes-kaniko-nginx/master/docker/Dockerfile"]
    volumeMounts:
    - mountPath: "/workspace"
      name: dockerfile-storage
  volumes:
    - name: kaniko-secret
      secret:
        secretName: regcred
        items:
          - key: .dockerconfigjson
            path: config.json
    - name: dockerfile-storage
      emptyDir: {}
